# Generated by Django 5.1.5 on 2025-02-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='manufacturing_filling',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='details',
        ),
        migrations.AddField(
            model_name='schedule',
            name='order_number',
            field=models.CharField(default='default_order_number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='personnel',
            field=models.CharField(default='default_personnel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='product_name',
            field=models.CharField(default='default_product_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='product_number',
            field=models.CharField(default='default_product_number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='production_date',
            field=models.CharField(default='default_production_date', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='production_quantity',
            field=models.CharField(default='default_production_quantity', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_center_name',
            field=models.CharField(default='default_work_center_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_center_number',
            field=models.CharField(default='default_work_center_number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='work_order_status',
            field=models.CharField(default='default_work_order_status', max_length=100),
            preserve_default=False,
        ),
    ]
