# Generated by Django 5.1.5 on 2025-02-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_rename_date_schedule_manufacturing_filling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='manufacturing_filling',
            field=models.CharField(max_length=100, verbose_name='製造/充填'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='ｵｰﾀﾞｰNo.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='personnel',
            field=models.CharField(max_length=100, verbose_name='人員'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='product_number',
            field=models.CharField(max_length=100, verbose_name='品番'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='production_date',
            field=models.CharField(max_length=100, verbose_name='生産日'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='production_quantity',
            field=models.CharField(max_length=100, verbose_name='生産予定数'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_center_name',
            field=models.CharField(max_length=255, verbose_name='ﾜｰｸｾﾝﾀｰ名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_center_number',
            field=models.CharField(max_length=100, verbose_name='ﾜｰｸｾﾝﾀｰ番号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='work_order_status',
            field=models.CharField(max_length=100, verbose_name='Work Order Status'),
        ),
    ]
