# Generated by Django 5.1.5 on 2025-03-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_schedule_manufacturing_filling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAppSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturing_filling', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('personnel', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('product_number', models.CharField(max_length=100)),
                ('production_date', models.CharField(max_length=100)),
                ('production_quantity', models.CharField(max_length=100)),
                ('work_center_name', models.CharField(max_length=255)),
                ('work_center_number', models.CharField(max_length=100)),
                ('work_order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=50)),
                ('sequence_number', models.IntegerField()),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule_app.scheduleappschedule')),
            ],
            options={
                'ordering': ['assigned_date', 'line_number', 'sequence_number'],
                'unique_together': {('line_number', 'sequence_number', 'assigned_date')},
            },
        ),
    ]
