# Generated by Django 5.1.5 on 2025-03-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='材料品番')),
                ('material_name', models.CharField(max_length=255, verbose_name='材料名')),
                ('unit', models.CharField(max_length=20, verbose_name='単位')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
                'ordering': ['material_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='製品品番')),
                ('product_name', models.CharField(max_length=255, verbose_name='製品名')),
                ('production_line', models.CharField(max_length=50, verbose_name='生産ライン')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.CharField(max_length=50, verbose_name='関連ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_type', models.CharField(max_length=20, verbose_name='単位種別')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='材料')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
