# Generated by Django 5.1.1 on 2024-09-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('生産日', models.TextField(blank=True, null=True)),
                ('ワーク', models.BigIntegerField(blank=True, null=True)),
                ('品番', models.TextField(blank=True, null=True)),
                ('製品名', models.TextField(blank=True, null=True)),
                ('生産数', models.BigIntegerField(blank=True, null=True)),
                ('縦', models.BigIntegerField(blank=True, null=True)),
                ('横', models.BigIntegerField(blank=True, null=True)),
                ('色', models.TextField(blank=True, null=True)),
                ('その他', models.BigIntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'schedule2',
                'managed': False,
            },
        ),
    ]
