# Generated by Django 5.1.1 on 2024-09-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=32, verbose_name='品番')),
                ('item_name', models.CharField(max_length=256, verbose_name='製品名')),
                ('specific', models.CharField(blank=True, max_length=20, null=True, verbose_name='特殊')),
                ('cap', models.CharField(blank=True, max_length=20, null=True, verbose_name='キャップ')),
                ('warning', models.TextField(blank=True, null=True, verbose_name='注意事項')),
                ('kind_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='品種番号')),
            ],
            options={
                'verbose_name': 'JP4',
                'verbose_name_plural': 'JP4製品一覧',
                'db_table': 'jp4_items',
            },
        ),
        migrations.CreateModel(
            name='Jp4InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='点検項目')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='機器名')),
                ('inspection_frequency', models.CharField(max_length=50, verbose_name='点検頻度')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='担当')),
            ],
            options={
                'verbose_name': 'JP4保守点検',
                'verbose_name_plural': 'JP4保守点検',
            },
        ),
        migrations.CreateModel(
            name='Jp4TroubleQuality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('発生日', models.DateField()),
                ('トラブル名', models.CharField(max_length=256)),
                ('トラブル内容', models.TextField(blank=True, null=True)),
                ('対策', models.TextField(blank=True, null=True)),
                ('分類', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'JP4品質トラブル',
                'verbose_name_plural': 'JP4品質トラブル',
                'db_table': 'jp4_trouble_quality',
            },
        ),
        migrations.CreateModel(
            name='Jp4TroubleSafety',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('発生日', models.DateField()),
                ('トラブル名', models.CharField(max_length=256)),
                ('トラブル内容', models.TextField(blank=True, null=True)),
                ('対策', models.TextField(blank=True, null=True)),
                ('分類', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'JP4安全トラブル',
                'verbose_name_plural': 'JP4安全トラブル',
                'db_table': 'jp4_trouble_safety',
            },
        ),
        migrations.CreateModel(
            name='Jp4InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('result', models.BooleanField(default=False)),
                ('manager_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jp4.jp4inspectionitem')),
            ],
            options={
                'verbose_name': 'JP4保守点検記録',
                'verbose_name_plural': 'JP4保守点検記録',
            },
        ),
        migrations.CreateModel(
            name='Jp4PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='PDF名')),
                ('file', models.FileField(upload_to='jp4_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jp4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='jp4.jp4')),
            ],
            options={
                'verbose_name': 'JP4 PDF',
                'verbose_name_plural': 'JP4 PDFs',
                'db_table': 'jp4_pdfs',
            },
        ),
    ]
